sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

matrix:
  fast_finish: true
  include:
    - os: windows
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

          packages:
            - g++-7
            - cmake
            - build-essential
            - tclsh
            - python3
            - python3-tk

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - eval "${MATRIX_EVAL}"

install:
  - export PATH=/usr/bin:$PATH

# Build steps
script:
        - rm -f src/*
	- rm -f headers/*

        #  - cmake --version
        #  - nmake -f Makefile
        #  - make
        #  - make test
    #  - sudo make install
    #  - make test_install
