# Enable C++ support
language: cpp

matrix:
  fast_finish: true
  include:
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0 --no-progress
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# Build steps
script:
        - source build_install.sh clean
        - source build_install.sh build
        - source build_install.sh release
        - source build_install.sh test_windows
          #- make
          #- make test
    #  - sudo make install
    #  - make test_install
