# Enable C++ support
language: cpp

matrix:
  fast_finish: true
  include:
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0 --no-progress
        - python --version
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

# Build steps
script:
        - cmake --version
        - mkdir -p build
	- cd build && cmake ../ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install
        - cd build && ctest --output-on-failure
          #- source build_install.sh
          #- make
          #- make test
    #  - sudo make install
    #  - make test_install
